name: markdown-miladiir
parent: default

matches:

   - trigger: "mdc"
     replace: "```\n$|$\n```"

   - trigger: "mdq"
     replace: "`$|$`"
     
   - trigger: "mdl"
     form: "[{{description}}]({{link}})"
     form_fields:
      description:
        default: "Description"
      link:
        default: "https://example.com"